### ISSUE TITLE
Misalignment of logo and "ember-toucan-core" in docs-app

### ISSUE THREAD

**Issue by nicolechung** [CrowdStrike/ember-toucan-core#114]
<img width="1365" alt="firefox" src="https://user-images.githubusercontent.com/771170/228897351-472375e7-b674-4c0a-b4c3-92b0b6ce1217.png">

Browser: Firefox
Browser version: 111.0.1 (64-bit)
OS: Ventura

**Comment by camskene** [comment]
The Calibre font is installed on my machine. If the font is activated or deactivated the alignment changes:
<img width="1605" alt="image" src="https://user-images.githubusercontent.com/507499/232111585-7ed2ab02-8d7f-4508-a2ab-edd514cdcc44.png">
