### ISSUE TITLE
pnpm-lock.yaml incompatible with PNPM 7

### ISSUE THREAD

**Issue by clintcs** [CrowdStrike/ember-toucan-core#171]
`pnpm-lock.yaml` is a version 6 lock file, which is incompatible with PNPM versions older than 8. Package installation can be made to fail immediately if an incompatible PNPM version is detected using `package.json`'s `engines` field. PR welcome?

**Comment by clintcs** [comment]
Scratch that. PNPM 7 supports version 6 lock files. The issue was with _my_ version of: `7.14.2`. I'll report back.

**Comment by clintcs** [comment]
After some testing, it looks like they quietly added support in PNPM 7 for version 6 lock files sometime around `7.24.2`. So we'd set `engines` in `package.json` to at least `"7.24.2"`.

However, they bumped the lock file version again—to 6.1—at [`7.33.0`](https://github.com/pnpm/pnpm/releases/tag/v7.33.0) for PNPM 7 and [`8.6.0`](https://github.com/pnpm/pnpm/releases/tag/v8.6.0) for PNPM 8. So we may want to require `7.33.0` or `8.6.0` if we want those running newer PNPM releases to not get a `pnpm-lock.yaml` diff upon running `pnpm install`, which we're seeing [in CI](https://github.com/CrowdStrike/ember-toucan-core/actions/runs/5190081381/jobs/9383748794#step:4:176).

Question about CI. Anyone know why we're [logging lock file differences](https://github.com/CrowdStrike/ember-toucan-core/blob/e9c8330fab06e0fbdef7842e8c70d5d5de57a957/.github/actions/pnpm/action.yml#L18) but not failing the build?

**Comment by vitch** [comment]
We should manage the `pnpm` version via volta as mentioned in CrowdStrike/ember-headless-table#184

**Comment by clintcs** [comment]
It's unfortunate that Volta uses a non-standard field (`volta`) in `package.json`. I'm fine using it for our convenience. 
However, I think we should also use the standard `engines` field. We can't guarantee that consumers use Volta and we should prevent them from using versions of PNPM that won't work.
