### ISSUE TITLE
VS Code settings: format on save

### ISSUE THREAD

**Issue by nicolechung** [CrowdStrike/ember-toucan-core#179]
Can the VS code settings include `format on save`?

Reason being, I need to turn OFF format on save for other projects but need it on for this one...

**Comment by ynotdraw** [comment]
We don't actually include any default VS Code settings by default, but you can definitely adjust yours as needed!  Should be done through https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings, then search for "format on save".  As long as you're on the Workspace tab there, it'll only apply to this particular repo/workspace and not the others.

Hope this helps!

**Comment by nicolechung** [comment]
Sweet! Will do this!
