### ISSUE TITLE
Call preventDefault() when clicking a disabled button

### ISSUE THREAD

**Issue by simonihmig** [CrowdStrike/ember-toucan-core#302]
As discussed elsewhere, when a `type="submit"` button has `@isDisabled` set, it does not prevent submitting the form, because the disabled state (for a11y reasons) does not add the `disabled` attribute. So we should call `event.preventDefault()` in the click handler in that case.

**Comment by ynotdraw** [comment]
Thanks for filing this.  I'll try to get to this between other work this week

**Comment by simonihmig** [comment]
Closed by https://github.com/CrowdStrike/ember-toucan-core/pull/304
