### ISSUE TITLE
Test app: lint fix does not autosort imports

### ISSUE THREAD

**Issue by nicolechung** [CrowdStrike/ember-toucan-core#43]
<img width="1058" alt="Screen Shot 2023-02-22 at 10 34 19 AM" src="https://user-images.githubusercontent.com/771170/220672697-9687cf12-3ded-46fe-b10a-6f0c4dd5f46c.png">

**Comment by NullVoxPopuli** [comment]
apologies, I still haven't fixed `--fix` with gjs/gts and eslint -- been prioritizing other things. :see_no_evil: 
Here is the tracking issues on eslint-plugin-ember though: https://github.com/ember-cli/eslint-plugin-ember/issues/1750
