### ISSUE TITLE
When will a release happen? (beta?)

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/ember-toucan-core#68]
Looks like there are a good  few components available for use now: https://ember-toucan-core.pages.dev/docs/installation

**Comment by ynotdraw** [comment]
@NullVoxPopuli we just released https://github.com/CrowdStrike/ember-toucan-core/releases/tag/%40crowdstrike%2Fember-toucan-core%400.1.0-beta.0 with some of our components!  We'll be adding changesets and doing releases more regularly from here on!

**Comment by NullVoxPopuli** [comment]
yay!!!
