### ISSUE TITLE
Consider adjusting CheckboxGroupField and Checkbox control component APIs

### ISSUE THREAD

**Issue by ynotdraw** [CrowdStrike/ember-toucan-core#88]
Relevant discussion: https://github.com/CrowdStrike/ember-toucan-core/pull/81#discussion_r1143491402

Do we want what is described in that comment instead?

cc: @simonihmig @nicolechung

**Comment by nicolechung** [comment]
```
<Form::CheckboxField
  @label='Label'
  {{! currently this is "@value" instead }}
  @isChecked={{this.value}}
  @onChange={{this.updateValue}}
/>
```

To me this seems more intuitive, having a @isChecked.

**Comment by simonihmig** [comment]
> To me this seems more intuitive, having a @isChecked.

Yeah, I agree
